import type { User, Pet, ScanLog, Notification } from "@/types";

export const MOCK_USER: User = {
  id: "u1",
  name: "Nguyen Loc",
  email: "loc@pawtag.vn",
  phone: "+84912345678",
  avatar: "https://images.unsplash.com/photo-1640384974326-347e7e3a9e4f?w=80&q=80",
  city: "Ho Chi Minh City",
};

export const MOCK_PETS: Pet[] = [
  {
    id: "p1",
    ownerId: "u1",
    name: "Bobby",
    species: "dog",
    breed: "Pembroke Welsh Corgi",
    gender: "male",
    birthDate: "2023-03-15",
    ageMonths: 24,
    weight: "12.5 kg",
    color: "Brown & White",
    photo: "https://images.unsplash.com/photo-1612940960267-77571294d37f?w=400&q=80",
    status: "safe",
    tagCode: "A8K92X",
    phone: "+84912345678",
    emergencyMessage:
      "Bobby is very friendly! Please call me right away. He loves treats and will come if you say his name. 🙏",
    scansToday: 3,
    totalScans: 24,
    medical: {
      allergies: "None",
      conditions: "Healthy, up-to-date on all vaccinations",
      medications: "None",
      bloodType: "DEA 1.1+",
      microchipId: "985141007548723",
      lastVetVisit: "2026-05-10",
      vetName: "Dr. Minh Tuan",
      vetPhone: "+84908123456",
    },
  },
  {
    id: "p2",
    ownerId: "u1",
    name: "Luna",
    species: "dog",
    breed: "Golden Retriever",
    gender: "female",
    birthDate: "2025-01-20",
    ageMonths: 12,
    weight: "25 kg",
    color: "Golden",
    photo: "https://images.unsplash.com/photo-1602241628512-1a66af5f3b00?w=400&q=80",
    status: "safe",
    tagCode: "B3M74Y",
    phone: "+84912345678",
    emergencyMessage: "Luna is friendly and loves people. Please contact me immediately! 🐾",
    scansToday: 0,
    totalScans: 6,
    medical: {
      allergies: "Pollen (mild)",
      conditions: "Healthy",
      medications: "None",
      bloodType: "DEA 1.1-",
      microchipId: "985141007548724",
      lastVetVisit: "2026-04-22",
      vetName: "Dr. Minh Tuan",
      vetPhone: "+84908123456",
    },
  },
];

export const MOCK_SCANS: ScanLog[] = [
  {
    id: "s1",
    petId: "p1",
    petName: "Bobby",
    petAvatar: MOCK_PETS[0].photo,
    location: "Quy Nhon Beach, Binh Dinh",
    lat: 13.7765,
    lng: 109.2237,
    timestamp: "2026-06-22T09:14:00Z",
    timeAgo: "2 min ago",
  },
  {
    id: "s2",
    petId: "p1",
    petName: "Bobby",
    petAvatar: MOCK_PETS[0].photo,
    location: "Nguyen Hue Street, HCMC",
    lat: 10.7769,
    lng: 106.7009,
    timestamp: "2026-06-21T15:32:00Z",
    timeAgo: "Yesterday, 15:32",
  },
  {
    id: "s3",
    petId: "p2",
    petName: "Luna",
    petAvatar: MOCK_PETS[1].photo,
    location: "District 1, Ho Chi Minh City",
    lat: 10.7763,
    lng: 106.7003,
    timestamp: "2026-06-21T11:05:00Z",
    timeAgo: "Yesterday, 11:05",
  },
  {
    id: "s4",
    petId: "p1",
    petName: "Bobby",
    petAvatar: MOCK_PETS[0].photo,
    location: "Hanoi Old Quarter",
    lat: 21.0285,
    lng: 105.8542,
    timestamp: "2026-06-20T08:20:00Z",
    timeAgo: "Jun 20, 08:20",
  },
  {
    id: "s5",
    petId: "p2",
    petName: "Luna",
    petAvatar: MOCK_PETS[1].photo,
    location: "Thu Duc City, HCMC",
    lat: 10.8458,
    lng: 106.7755,
    timestamp: "2026-06-18T14:50:00Z",
    timeAgo: "Jun 18, 14:50",
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "n1",
    type: "scan",
    title: "Bobby was scanned!",
    body: "Someone found Bobby at Quy Nhon Beach, Binh Dinh.",
    time: "2 min ago",
    unread: true,
    petId: "p1",
    petAvatar: MOCK_PETS[0].photo,
  },
  {
    id: "n2",
    type: "location",
    title: "Location shared",
    body: "A finder shared their location near District 1, HCMC.",
    time: "1 hour ago",
    unread: true,
    petId: "p1",
  },
  {
    id: "n3",
    type: "scan",
    title: "Luna was scanned",
    body: "Luna's tag was scanned near Thu Duc City.",
    time: "3 hours ago",
    unread: false,
    petId: "p2",
    petAvatar: MOCK_PETS[1].photo,
  },
  {
    id: "n4",
    type: "medical",
    title: "Vaccine reminder",
    body: "Bobby's rabies vaccine expires in 30 days. Book a vet visit soon.",
    time: "Yesterday",
    unread: false,
    petId: "p1",
  },
  {
    id: "n5",
    type: "system",
    title: "Welcome to PawsTag!",
    body: "Your account is set up. Create your first pet profile to get started.",
    time: "Jun 20",
    unread: false,
  },
];
